name: Ruff Linter
on: push

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.PAT }}
    - uses: actions/setup-python@v2
    - run: pip install ruff
    - run: | 
        ruff check --fix .
    - uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: 'fix: ruff(style)'
